version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - attach_workspace:
          at: C:\circleci-workspace
      - checkout
      - run:
          name: Download Miniconda and save in tmp
          command: |
            $client = new-object System.Net.WebClient
            $client.DownloadFile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe","C:\tmp\Miniconda3-latest-Windows-x86_64.exe")
      - run:
          name: Run Miniconda installer in silent mode
          command: |
            C:\tmp\Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3
      - run:
          name: Update conda, install pack and create the riverlines environment from the environment.yml file
          command: |
            conda update conda
            conda install python=3.7
            Write-Host "$env:CONDA_ROOT"
      - run:
          name: Download GitHub based dependencies
          command: |
            $client = new-object System.Net.WebClient
            $client.DownloadFile("https://github.com/ausseabed/qajson/archive/master.zip","C:\tmp\ausseabed.qajson.zip")
            $client.DownloadFile("https://github.com/ausseabed/pyall/archive/master.zip","C:\tmp\pyall.zip")
            $client.DownloadFile("https://github.com/ausseabed/hyo2_mate/archive/master.zip","C:\tmp\hyo2.mate.zip")
            $client.DownloadFile("https://github.com/hydroffice/hyo2_abc/archive/master.zip","C:\tmp\hyo2.abc.zip")
      - run:
          name: Activate the qax conda environment, update the version and install the package
          command: |
            Write-Host "$env:CONDA_ROOT"
            conda install -y -c conda-forge certifi
            conda install -y -c conda-forge --file requirements_conda.txt
            conda install -y -c conda-forge --no-deps cartopy
            pip install coveralls
            pip install jsonschema
            pip install pytest
            pip install pytest-cov
            pip install setuptools==44.*
            pip install C:\tmp\ausseabed.qajson.zip
            pip install C:\tmp\pyall.zip
            pip install C:\tmp\hyo2.mate.zip
            pip install pypiwin32
            conda install -y -c conda-forge --no-deps pyproj
            pip install --no-deps C:\tmp\hyo2.abc.zip
            pip install .
      - run:
          name: Pack the environment and save it in the workspace
          command: |
            Write-Host "$env:CONDA_ROOT"
            pip install pyinstaller
            pyinstaller .\install\cli.spec
            ls
            ls C:\Users\circleci\project\dist
            New-Item -Path "C:\circleci-workspace\artifacts" -Name "logfiles" -ItemType "directory"
            Move-Item C:\Users\circleci\project\dist -Destination C:\circleci-workspace\artifacts
      - persist_to_workspace:
          root: C:\circleci-workspace\
          paths: artifacts

  # publish-github-release:
  #   docker:
  #     - image: cibuilds/github:0.10
  #   steps:
  #     - attach_workspace:
  #         at: ~/circleci-workspace
  #     - run:
  #         name: "Publish Release to github"
  #         command: |
  #           VERSION=${CIRCLE_TAG}
  #           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/circleci-workspace/artifacts/

workflows:
  version: 2
  Windows_Workflow:
    jobs:
      - build
      # - publish-github-release:
      #     requires:
      #        - build
